### ISSUE TITLE
predefined images do not work

### ISSUE THREAD

**Issue by jpengelbrecht** [nuxt-modules/og-image#145]
Using the url of predefined images doesnt work.  
for example
<img width="840" alt="image" src="https://github.com/nuxt-modules/og-image/assets/93583336/d52adbff-b849-4a38-96ee-5de4423d28f0">
from the docs i use this example
<img width="900" alt="image" src="https://github.com/nuxt-modules/og-image/assets/93583336/e16c75b3-e4cb-46a3-92c3-522dbd6ed479">
the above code will result in no OG image being generated. 

if i use  this example to render the template using an image inside a normal template 
<img width="820" alt="image" src="https://github.com/nuxt-modules/og-image/assets/93583336/e4016bb8-4ff6-426a-8f07-d0e02a7a36d0">

i get the following error.  
<img width="823" alt="image" src="https://github.com/nuxt-modules/og-image/assets/93583336/6f4a32e8-d836-484e-a3ae-a669ebcb9a71">

also  as a final note,  i also noted that this og image rendered doesn't like webp usage and breaks whenever i try use it. 

here is a test repo https://github.com/jpengelbrecht/nuxt-seo-route-rules-issue/blob/main/app.vue

**Comment by harlan-zw** [comment]
> the above code will result in no OG image being generated.

it shouldn't generate an OG Image, it should just add the meta tags pointing to this file? It just acts as a shorthand for avoiding to manually define all of the tags

**Comment by jpengelbrecht** [comment]
@harlan-zw so the odd thing is.  
<img width="799" alt="image" src="https://github.com/nuxt-modules/og-image/assets/93583336/befe5834-7218-4ed1-93a7-4e4482fc3a84">
works on playground 
<img width="902" alt="image" src="https://github.com/nuxt-modules/og-image/assets/93583336/d6b5b68d-2bc3-4c84-a8e8-a43b0abc400b">


however it doesn't  work on generate.  it gives this error 
<img width="737" alt="image" src="https://github.com/nuxt-modules/og-image/assets/93583336/2936e7bc-ff28-452c-af1a-4b5c80a70228">


then  using this way 
<img width="805" alt="image" src="https://github.com/nuxt-modules/og-image/assets/93583336/7dc72cbb-5909-4d8c-b181-2f911c7443b5">
shows this in the generator 
<img width="1077" alt="image" src="https://github.com/nuxt-modules/og-image/assets/93583336/73f69a12-546f-4a7e-a9bc-9f8fabdc7102">

**Comment by harlan-zw** [comment]
Can you share a reproducgtion so I can see what's going on?

For the second issue, this is a known issue for predefined images, see https://github.com/nuxt-modules/og-image/issues/129. You should use a third-party tool to preview the og image if you want to verify it (Nuxt DevTools also has issues).

**Comment by jpengelbrecht** [comment]
@harlan-zw  here you go https://github.com/jpengelbrecht/nuxt-seo-route-rules-issue/blob/main/app.vue

**Comment by harlan-zw** [comment]
Thanks, sorry missed it the first time :laughing: 

I've pushed up a fix for the prerendering issue in 3.0.0-rc.27

**Comment by jpengelbrecht** [comment]
no stress dude!  you have been fixing these patches like a mad man,  really appreciate the effort you put in man
