### ISSUE TITLE
https://0.0.0.0:3000/__og-image__/font/Inter/400.ttf" - 404 on production

### ISSUE THREAD

**Issue by aloky** [nuxt-modules/og-image#147]
`https://0.0.0.0:3000/__og-image__/font/Inter/400.ttf` - 404 on production, how i can set correct url?

**Comment by aloky** [comment]
im set in `nuxt.config` > `site` > `url: "https://example.com"`, doesnt help

**Comment by aloky** [comment]
nginx and app start in docker,

- nginx sets server url.com listen  http://frontend:3000 etc
- but app build on http://frontend:3000 in docker

and i have `[GET] "https://frontend:3000/__og-image__/font/Inter/400.ttf": <no response> fetch failed` error

**Comment by harlan-zw** [comment]
Thanks, I have an idea how to fix this but will be a few days.

**Comment by harlan-zw** [comment]
Hi, please try out nuxt-og-image@3.0.0-rc.35 and let me know how you go :)

**Comment by aloky** [comment]
Thank you, its ok.
