### ISSUE TITLE
og-image does not work on azure deployment - Nuxt 3

### ISSUE THREAD

**Issue by moshetanzer** [nuxt-modules/og-image#148]
Hi @harlan-zw, 

Thanks for your amazing lib.

When i take the image url that is being created for og image and try access it, i get 
{
    "code": 400,
    "message": "Login not supported for provider azureStaticWebApps"
}

The OG images does not display neither on Facebook, twitter etc or when accessed directly.

When accessed directly using azure url (which strangely is the one used in og image link) than get error 400. Else when use custom domain - get 404 inter font not found.

Stack is;

Nuxt 3.9.2 with Nitro 2.8.1 - SSR - Azure deployed with Github Actions

**Comment by harlan-zw** [comment]
Should be fixed with 3.0.0-rc.36, let me know how you go :)

**Comment by moshetanzer** [comment]
Hi Harlan, Thanks so much. Will give it a try a bit later and let you know. Really appreciate! thanks
