### ISSUE TITLE
nuxt-icon vs/and unocss icon

### ISSUE THREAD

**Issue by husayt** [nuxt-modules/og-image#149]
Currently og-image uses nuxt-icon for generating svg icons. Similar functionality is also present in [uno css](https://unocss.dev/presets/icons). For those already using unocss, it will be more efficient and consistent to use uno css functionality for this. Is it possible to provide a choice ?

**Comment by harlan-zw** [comment]
Nuxt-icon was a dependency but has since been dropped.

The icon implementation is just to quickly get you started with customizing one of the community templates, it's better that you build your own template and use whichever icons you prefer.
