### ISSUE TITLE
enabled: false on config breaks app because defineOgImageComponent() composable wont exist

### ISSUE THREAD

**Issue by jpengelbrecht** [nuxt-modules/og-image#152]
i think for me atleast the enabled flag is useful when you have more than one environment and want to toggle it on and off depending on environment,  especially because it makes the builds alot slower.  

since the new version as it now relies on composeeables this is no longer possible.  It would be amazing if there was a way to include it in the project but still optionally choose whether to run it or not

**Comment by harlan-zw** [comment]
Thanks for the suggestion, this is available in the latest RC.
