### ISSUE TITLE
Warn About CSS Inline Usage

### ISSUE THREAD

**Issue by harlan-zw** [nuxt-modules/og-image#154]
The `css-inline` module is currently disabled for:
- all Cloudflare environments
- vercel-edge (function size issue)

There is currently no warning for end user when they create a template that relies on the css-inline module that won't work at runtime.

**Comment by Stranger6667** [comment]
Is there anything I can do from the `css-inline` side? i.e. maybe more aggressive size optimization could decrease the module size if that's an issue

**Comment by harlan-zw** [comment]
I've had to change the logic so that _if_ a user tries to use the CSS inline feature it will prompt them to install the dependencies which will enable the integration. The usage was a bit too buggy (and too much overhead) to warrant keeping it enabled all the time unfortunately. 

Will close this for now but may revisit in the future.
