### ISSUE TITLE
German Umlauts not working

### ISSUE THREAD

**Issue by marcelxpfeifer** [nuxt-modules/og-image#159]
If text contains german umlauts (äöü) the HTML shows the correct letters

<img width="73" alt="image" src="https://github.com/nuxt-modules/og-image/assets/40826752/e93d11f4-8923-437a-bad4-871c2c5744ec">

 but the satori svg and png show:
 
<img width="264" alt="image" src="https://github.com/nuxt-modules/og-image/assets/40826752/f4fde9cc-2bcb-41aa-a2ac-29a9bf139465">

Not sure if its an issue of this module or if the issue is with satori

**Comment by marcelxpfeifer** [comment]
Found in the new v3 documentation that only english characters are enabled by default for Inter. A different font can be used. For more information check out: https://nuxtseo.com/og-image/guides/non-english-locales

**Comment by marcelxpfeifer** [comment]
Sorry to reopen the issue, but after trying to load different fonts from the Google API and using local fonts that support ÖÄÜ (which Inter should do as well). I can't seem to find out why umlauts are not working.
In addition after updating to the v3 Beta locally everything seems to work fine, but after deploying to Netlify, umlauts are again broken.

**Comment by harlan-zw** [comment]
Would it be possible to get a [reproduction](https://stackblitz.com/edit/nuxt-starter-pxs3wk?file=pages/index.vue)? Seems to be working for me

![image](https://github.com/nuxt-modules/og-image/assets/5326365/eba5e4a1-9927-46c9-b7e7-f3c1804adea8)

**Comment by marcelxpfeifer** [comment]
Yes will try to provide one later today, but like I said locally it's working fine, only when I deploy to Netlify it breaks.

**Comment by harlan-zw** [comment]
Oh I see, I'll try doing a deployment with them

**Comment by harlan-zw** [comment]
I have tried prerendering and building locally and they seem to be working correctly. I'll need a reproduction to investigate further.
