### ISSUE TITLE
Firebase deploy Failure on MacBook M1: Incorrect Platform Detection for @css-inline/css-inline-darwin-arm64

### ISSUE THREAD

**Issue by harlan-zw** [nuxt-modules/og-image#170]
https://github.com/unjs/nitro/issues/2096

**Comment by harlan-zw** [comment]
This issue will be solved when the latest css-inline WASM is stable (see https://github.com/Stranger6667/css-inline/issues/341).

Not sure what else you mean, it should work on Firebase afaik

**Comment by harlan-zw** [comment]
I think the issue is that you have within your lock file that the `resvg` dependency should deploy using the Mac binary, but Firebase uses Linux.

You can try and solve by running `npm install -f` as a first step, which will force re-install the binary (maybe). I'm guessing `pnpm` doesn't have this issue.

**Comment by web-tailor** [comment]
I have the same issue. Macbook pro (2015) Intel i5. Disabling ogImage in nuxtseo is what I have done to solve the deployment issue. However, it's a shame we cannot use ogImage because of this.

**Comment by mfreeman451** [comment]
> This issue will be solved when the latest css-inline WASM is stable (see [Stranger6667/css-inline#341](https://github.com/Stranger6667/css-inline/issues/341)).
> 
> Not sure what else you mean, it should work on Firebase afaik

Seems like the issue was closed for the WASM thing.. whats the next step?

**Comment by alexpilugin** [comment]
I have the same issue.
MacBook Air 1.6 GHz Dual-Core Intel Core i5
node v18.19.0
firebase v13.13.0

**Comment by harlan-zw** [comment]
I think I can solve this by only using the wasm build but it will slow down production node apps so bit of a trade off. Will investigate further when I have a chance.

The workaround I posted should solve it temporarily though

**Comment by harlan-zw** [comment]
This should no longer be causing issues in 3.0.0-rc.57.
