### ISSUE TITLE
Community section missing?

### ISSUE THREAD

**Issue by reallymello** [nuxt-modules/og-image#175]
Trying to follow the documentation on https://nuxtseo.com/og-image/getting-started/getting-familar-with-nuxt-og-image

but it links to places like
https://github.com/harlan-zw/nuxt-og-image/blob/main/src/runtime/components/Templates/Community/SimpleBlog.vue

which no longer exist

![image](https://github.com/nuxt-modules/og-image/assets/18431256/dcf20062-51c1-479c-8086-c8a8a2b4f6b8)

Have things changed recently?

**Comment by harlan-zw** [comment]
Looks like @yoo-minho recently fixed this up for us :raised_hands:
