### ISSUE TITLE
How do I get the rendered image to og:image useSeoMeta

### ISSUE THREAD

**Issue by Zafiiovskiy** [nuxt-modules/og-image#185]
Really love what you are doing, but maybe I lost something in documentation. 

My index.ts has useSeoMeta, useHead and defineOgImageComponent. I can see the Og image in Og-image preview in dev tools but not as a og:image in open graph preview. I assume the image has to be generated somewhere for me to reference as a url string in useSeoMeta, but I can't find it.

Can you please help? @harlan-zw 

<img width="516" alt="image" src="https://github.com/nuxt-modules/og-image/assets/51366127/5e53357a-fe19-4b56-aca7-72895450f2c2">

<img width="737" alt="image" src="https://github.com/nuxt-modules/og-image/assets/51366127/1e2b21c1-3396-49c0-b5f4-6d8532117217">

**Comment by harlan-zw** [comment]
Hi, please use the OG Image DevTools tab. The tab you're using is broken for displaying the proper og images.

**Comment by Zafiiovskiy** [comment]
@harlan-zw Thank you! It does work well for domain specified in your here:
`defineNuxtConfig({site: {
    url: 'https://www.your-domain.com', 
  }}`

Leaving this here so anybody confused like I was will have an explanation
