### ISSUE TITLE
defineOgImageComponent with dynamic values not working

### ISSUE THREAD

**Issue by Zafiiovskiy** [nuxt-modules/og-image#190]
Hi! trying to make defineOgImageComponent work with dynamic data that I get from CMS api in OnMonted for Nuxt3. 

`useSeoMeta({
    description: () => descriptionMeta.value,
})`

the `() => prop` for useSeoMeta is working great for me but unfortunately defineOgImageComponent does not work like that and creates an image with emty or default values even if i give it ref or computed properties.

Do you know any way to make it work?

**Comment by harlan-zw** [comment]
Hey, thanks for the issue.

>  from CMS api in OnMonted for Nuxt3.

OG Image data needs to be defined within the Server Side response, if your data is only available onMounted then it will always be empty as this is only called on the client side. `useSeoMeta`  would be showing you the right thing when you inspect the HTML but the SSR response still wouldn't have the meta (try view the page source).

You'll need to fetch the data top-level to fix this, if you still have issues please make a reproduction.
