### ISSUE TITLE
Error if a png image is included into a og image

### ISSUE THREAD

**Issue by maximepvrt** [nuxt-modules/og-image#194]
error message "Invalid JPEG"

ex : https://avatars.githubusercontent.com/u/44604921 https://github.com/nuxt/nuxters/issues/66

https://nuxters.nuxt.com/card/maximepvrt/og.png => OK (jpeg avatar)
https://nuxters.nuxt.com/card/shinGangan/og.png => KO (png avatar)

**Comment by maximepvrt** [comment]
@harlan-zw An idea of ​​the problem ?

**Comment by harlan-zw** [comment]
Thanks again for the PR, now available in RC 53
