### ISSUE TITLE
support zero-runtime when prerendering

### ISSUE THREAD

**Issue by danielroe** [nuxt-modules/og-image#210]
When fully prerendering all static pages, it would be nice to support a mode where there is no server footprint.

For example, in [this PR](https://github.com/danielroe/roe.dev/pull/1400), `nuxt-og-image` adds some overhead (200kB+ to server runtime, and 1.2Mb+ to node_modules) which ideally I would like to avoid - as in my case I know it is not needed once the pages are prerendered.

**Comment by harlan-zw** [comment]
This is technically supported already but the DX isn't great (not properly documented either).

```ts
export default defineNuxtConfig({
  ogImage: {
    compatibility: {
       runtime: {
         'chromium': false,
         'satori': false,
         'css-inline': false,
         'resvg': false,
         'sharp': false,
       }
    }
  }
})
```

It would be nice to support a zero-config option for this but seems like it could cause some issues :thinking:

**Comment by danielroe** [comment]
I think I tried that in the linked PR but it is not sufficient due to other runtime code that is added, such as for nuxt-site-config, a Nuxt content integration, and possibly other plugins.

**Comment by harlan-zw** [comment]
I'd like to support this but it's partially blocked by Nuxt Kit tooling.

Ideally, we'd be able to register routes or plugins that only register during prerender. 

It can be solved but will require migrating to dynamic templates that noop out for non-prerender environments, I'd like to avoid adding this complexity to the templates at this time.

**Comment by harlan-zw** [comment]
This will be available in the v3 stable which will drop very shortly
