### ISSUE TITLE
the module seems to add significant overhead to unrelated parts of the app

### ISSUE THREAD

**Issue by warflash** [nuxt-modules/og-image#213]
I noticed our API response times increased significantly when using the og-image module.
 On our production instance the difference goes from around ~40ms avg to ~110ms avg depending on whether the module is on or off.

I feel it's difficult to share a proper reproduction, but the perf difference forces us to disable the module entirely

**Comment by warflash** [comment]
I wasn't quite happy with the reproduction as on vercel it's very tricky to see. Also it seems like https://github.com/harlan-zw/nuxt-schema-org is also affected by this.

I ran a flamegraph perf test of the node server and those are the results for with the 2 modules:
Flamegraph download: [with-og-schema.cpuprofile](https://github.com/user-attachments/files/15525486/with-og-schema.cpuprofile)
![image](https://github.com/nuxt-modules/og-image/assets/22006082/adc7957e-cc76-4fa3-ad76-eb9e2e0e5609)

Both modules disabled:
Download: [no-og-schema.cpuprofile](https://github.com/user-attachments/files/15525489/no-og-schema.cpuprofile)
![image](https://github.com/nuxt-modules/og-image/assets/22006082/4bdd2d5a-a46d-49ce-9ba9-b9ebd2e60291)

Something about the way the modules use runtime config seems to add a flat 60ms processing time to every route ever visited

**Comment by harlan-zw** [comment]
Hi @warflash, sorry for the delay on this.

I did an initial investigation and couldn't see anything wrong within the module code. This seems to be related to `useRuntimeConfig()` not using the cached result between calls, an upstream issue with Nitro.

Could you confirm the Nitro and OG Image versions you're using if it's still an issue for you?
