### ISSUE TITLE
satoriOptions width and height crop the image instead of reducing resolution

### ISSUE THREAD

**Issue by mahmoudyusof** [nuxt-modules/og-image#215]
using satoriOptions as follows
```js
  ogImage: {
    satoriOptions: {
      width: 600,
      height: 315,
    },
  },
```
results in the attached image
![image](https://github.com/nuxt-modules/og-image/assets/16169419/d2b18813-137e-47c9-8f05-e4a686c659f7)

instead of reducing the resolution, it just cropped the image.

The component on which the image is based doesn't use fixed pixel width and height, instead it uses tailwind's `h-full` and `w-full` classes, but should this affect the output?

**Comment by harlan-zw** [comment]
Hey, if you'd like to change the resolution please use the `defaults`.

```ts
export default defineNuxtConfig({
  ogImage: {
    defaults: {
      width: 600,
      height: 315,
    },
  }
})
```

This is used to inform the size of the template that satori tries to render.
