### ISSUE TITLE
How to Upload images to Cloudflare Images

### ISSUE THREAD

**Issue by besnikh** [nuxt-modules/og-image#221]
Hi, 

I've read the documentation many times but still didn't figure it out on how to upload image to cloudflare ? 

- I am using Cloudflare Pages to host the Nuxt.js 3 - works fine

On Local Dev when I use DevTools I can see OG-Images beeing rendered as I it should which is great. 

However, since my website is dynamic, I need to dynamically "upload" those OG-Images to Cloudflare 

When I deployed my Nuxt.js 3 app to Cloudflare pages I got this in sourc:

<meta property="og:image" content="https://website.com/__og-image__/image/router/router-name/og.png">
 

Any hint help is needed please..

**Comment by harlan-zw** [comment]
Hi, not too sure what you mean.

The images are generated dynamically at runtime, they shouldn't be uploaded anywhere. If you want to use a persistent cache storage see [Caching Images](https://nuxtseo.com/og-image/guides/cache).

**Comment by besnikh** [comment]
Hi @harlan-zw 

Here is an example: 

I upladed the project on Cloudflare Pages: 

[https://aihive-front.pages.dev/ai-tools-news/10-cutting-edge-ai-tools-transforming-social-media-and-content-creation-in-2024](url)

And this is the generated image on runtime: 

`view-source:https://aihive-front.pages.dev/ai-tools-news/10-game-changing-ai-tools-transforming-businesses-in-2024`

Which is not working 

and this is inside script setup: 

```
defineOgImageComponent('Article', {
  articleTitle: aiarticle.value?.name || 'Default Article Title',
  brandImageSrc: 'https://imagedelivery.net/Wi6_E62agkkvW3RsmnEvAw/0285ec60-08e2-44d8-082f-c42f687bff00/100',
  brandImageAlt: aiarticle.value?.name || 'Default Article Name',
  brandImageWidth: 200,
  brandImageHeight: 200
});

useHead({
  title: `${aiarticle.value.name} - AI Hive Tools`,
  htmlAttrs: {
    lang: 'en',
  },
  link: [
    {
      rel: 'canonical',
      href: `https://aihive.tools/ai-tools-news/${slug}`,
    },
  ],
  meta: [
    { name: 'description', content: `${aiarticle.value.name}` },
    { property: 'og:title', content: `${aiarticle.value.name} - AI Hive Tools` },
    { property: 'og:description', content: `${aiarticle.value.name}` },
    { property: 'og:type', content: 'article' },
    { property: 'og:url', content: `https://aihive.tools/ai-tools-news/${slug}` },
    { property: 'og:image', content: '' },
    { name: 'twitter:card', content: 'summary_large_image' },
    { name: 'twitter:title', content: `${aiarticle.value.name} - AI Hive Tools` },
    { name: 'twitter:description', content: `${aiarticle.value.name}` },
    { name: 'twitter:image', content: '' },
    { property: 'og:locale', content: 'en_US' },
    { property: 'og:site_name', content: 'AIHive.tools' },
    { name: 'robots', content: 'index, follow' },
  ],
});
```

Once again, the image is being generated on DevTools great, but when I deploy the web app now I don't have any image.

Am I missing something ?

**Comment by harlan-zw** [comment]
The image is working correctly https://aihive-front.pages.dev/__og-image__/image/ai-tools-news/10-cutting-edge-ai-tools-transforming-social-media-and-content-creation-in-2024/og.png

The problem is you have the site URL set to a different domain

**Comment by besnikh** [comment]
@harlan-zw omg, time to sleep, I was playing with this for more than 12 hours setting everything up and I knew I'm missing something. 

Thank you!
