### ISSUE TITLE
`baseURL` get duplicated for the url of `og:image`

### ISSUE THREAD

**Issue by n0099** [nuxt-modules/og-image#228]
Even after this attempted fix: 5c08cfa7202ff2b938471c3db0d0748ee6eea71b
https://stackblitz.com/edit/nuxt-starter-cusggt
![image](https://github.com/nuxt-modules/og-image/assets/13030387/0fb42c76-75c8-4faa-b5cd-9d3662ef9543)
Only occurs when nuxt pages is enabled (with `vue-router`), if you do
```bash
mv pages/index.vue app.vue
rm -r pages
```
then the `baseURL` won't duplicate.

**Comment by harlan-zw** [comment]
Can you check the reproduction? It doesn't seem right to what you're showing me

![image](https://github.com/nuxt-modules/og-image/assets/5326365/d59bee2e-ace4-4abd-987f-2808aa84c541)

**Comment by n0099** [comment]
I forgot to save this stackblitz after `.env` created
```env
NUXT_APP_BASE_URL=/base
```

**Comment by n0099** [comment]
It only occurs when using [`nuxt-og-image@3.0.0-rc.54`](https://github.com/nuxt-modules/og-image/releases/tag/v3.0.0-rc.54): https://stackblitz.com/edit/nuxt-starter-pvaeyd (manually add `.env` is required), seems https://github.com/nuxt-modules/og-image/pull/231 fix this

**Comment by n0099** [comment]
Also on [`nuxt-og-image@3.0.0-rc.55`](https://github.com/nuxt-modules/og-image/releases/tag/v3.0.0-rc.55).

**Comment by harlan-zw** [comment]
Thank you @n0099, this looks like it was an issue with something upstream appending the baseURL to the host (nitro or nuxt).

The URL resolving is handled by the Nuxt Site Config module which I've pushed up a fix for in and is used in the latest RC 56 of this module.
