### ISSUE TITLE
Seems so have issues with nuxt@3.12.3

### ISSUE THREAD

**Issue by toniengelhardt** [nuxt-modules/og-image#232]
Getting this error on dev server start with nuxt-og-image@3.0.0-rc.54 and nuxt@3.12.3. No issues with nuxt@3.12.2.

<img width="821" alt="Screenshot 2024-07-02 at 22 10 26" src="https://github.com/nuxt-modules/og-image/assets/2703233/b5c8e91c-1c50-41ae-b838-5e0ca0892544">

**Comment by harlan-zw** [comment]
Hi, thanks for the issue. Please try the latest version nuxt-og-image@3.0.0-rc.55

**Comment by ptdev** [comment]
Hi, we've also been hit by this issue.

But we're using the full @nuxt/seo package which apparently didn't have it's og-image dependency updated with this latest fix.

Is there anyway to get this without adding the og-image package as a top level dependency?

Thanks, cheers.

**Comment by toniengelhardt** [comment]
Thanks for the quick fix @harlan-zw, works 🙏

@ptdev for now you can add this to your `package.json`, I'm also using it with `@nuxtjs/seo`.

```
"resolutions": {
    "nuxt-og-image": "^3.0.0-rc.55"
}
```
