### ISSUE TITLE
Can't use the image generation : Get 404  Page not found: /__nuxt-og-image

### ISSUE THREAD

**Issue by Eyap53** [nuxt-modules/og-image#234]
Hello ! 

Not sure if this is an issue or a misconfiguration on my side, but I have been trying to solve this for the past two days without success.
I followed the tutorial at this link : https://nuxtseo.com/og-image/getting-started/getting-familar-with-nuxt-og-image#part-1-using-an-og-image.
It worked once or twice, and while making a few other changes, and coming back to it I got an error : 404  Page not found: /__nuxt-og-image while trying to access the generated image.
Tried to undo, and still got the error.
I tried on another project, and same result. I tried to reinstall the package (I use pnpm), without success...

Tried to revert the changes to a previous state where it was working, same error...

Do you have any idea ?

Url of the project : https://github.com/Eyap53/nuxt-portfolio
It was working at this commit : https://github.com/Eyap53/nuxt-portfolio/tree/e91d2e1f7ad66cf24a7c43742cc5067be640db04.

Thanks a lot for your help, and more importantly for your work !

**Comment by szokeptr** [comment]
I have the same issue.

**Comment by harlan-zw** [comment]
Thanks for raising this issue, it should be fixed with RC 58

**Comment by Eyap53** [comment]
Tested with RC 59, it's working properly !

Thank you for your amazing work :stars:
