### ISSUE TITLE
Using <slot> in a component causes OgImage generation issues

### ISSUE THREAD

**Issue by BghinC** [nuxt-modules/og-image#241]
I have a template in `components/OgImage` called using `defineOgImageComponent`.
That template uses other components, but one of them uses `<slot>`. It used to work a couple of months ago.

I recently observed two different behaviors:

- In my project, the image is generated but the components using `<slot>` are not rendered in the image.
- I tried to reproduce the same thing in Stackblitz, but here the image generation fails. Removing the `<slot>` from the component fixes the image.

[You can find the reproduction here](https://stackblitz.com/edit/nuxt-starter-ix3vqa?file=components%2FOgImage%2FMyTemplateItem.vue)

**Comment by harlan-zw** [comment]
Thanks for the issue, I've taken a look and it appears to be an upstream Nuxt issue with using nested island components.

The simple workaround is to move the sub component into the components dir.

See https://stackblitz.com/edit/nuxt-starter-vdfkge?file=components%2Fglobals%2FMyTemplateItem.vue
