### ISSUE TITLE
Support .webp images? Currently this causes a server error 500

### ISSUE THREAD

**Issue by davemg3** [nuxt-modules/og-image#246]
Use of .png or .jpg image is allowed in source of image for OG image component but not .webp

` <img :src="logo" ;" />`

Tested with BrandedImage.vue template

> Error: [GET] "/__og-image__/image/og.json": 500 Internal Server Error

**Comment by harlan-zw** [comment]
Hi, if you'd like to use webp you will need to use the chromium renderer. Satori [does not support webp](https://github.com/vercel/satori/issues/273).

**Comment by davemg3** [comment]
ok thanks @harlan-zw To be noticed also some emoji wrong rendering. In 

> defineOgImageComponent

emojis gets not aligned with text. Some columns appears splitting text and creates wrong display. 
I wanted to complete this layout issues ;) feed but you were fast to answer on st point.

Here is a stackblitz to  show the case : https://stackblitz.com/edit/nuxt-starter-fe8yyu?file=pages%2Findex.vue
