### ISSUE TITLE
500 Image size cannot be determined. Please provide the width and height of the image

### ISSUE THREAD

**Issue by JulienHenrotin** [nuxt-modules/og-image#250]
### 🐛 The bug

I have a projet Nuxt 3 SSR. I tried to use og-image-nuxt but I have a problem when it's on production mode in my dev server. 
The image URL give me **`error 500 Image size cannot be determined. Please provide the width and height of the image.`** 

### Environement

**My dev server run with a node docker.** 
```
Node.js Version: 18.20.4 
npm Version: 10.7.0
```

**My packages versions**
```
    "nuxt": "3.12.4",
     "nuxt-og-image": "3.0.0-rc.64",
     "@nuxt/devtools": "1.3.9",
     "typescript": "5.5.4"
``` 

### Explanations

 I have **my page `invitation-[id].vue`.** I load data with `useLazyAsyncData `and I use these for generate an image in `defineOgImageComponent`.

_I already try to play with `defineOgImageComponent ` options but nothing change._ 

```typescript
<script setup lang="ts">
const { data: event, error } = await useLazyAsyncData(`get-event-${idEvent}`, () => services.getEvent(idEvent))
defineOgImageComponent('event', {
  userName: event.value?.eventOrganizer.name,
  picture: event.value?.eventOrganizer.picture,
}, {
  cacheMaxAgeSeconds: 0,
  alt: 'Invitation à sortir',
})
</script>
``` 

**My ogImage component :** `event.vue `
It's a simple component who just take two parameters and display a string and an image. 

_I already try with a simpler version (no background, no image, fixed sizes defined)._

```html
<template>
  <div class="h-screen w-full flex flex-col items-center bg-cover bg-top bg-no-repeat" :style="{ backgroundImage: 'url(https://henoo.fr/pictures/illustrations/landing/cloud.png)' }">
    <div class="flex flex-col items-center flex-grow justify-center">
      <NuxtImg v-if="picture" class="size-40 rounded-full mb-6" alt="user profile picture" :src="picture" />
      <div class="text-3xl text-center !font-semibold my-6">
        {{ userName }} t'invite à sortir
      </div>
    </div>
    <div class="mb-6">
      <NuxtImg src="https://henoo.fr/logo/logo_text.png" class="h-12" />
    </div>
  </div>
</template>

<script setup lang="ts">
withDefaults(defineProps<{ userName?: string, picture?: string }>(), {
  userName: 'Ton pote',
  picture: undefined,
})
</script>
``` 

Config OG Image Nuxt 

```typescript
export default defineNuxtConfig({
 ogImage: {
    debug: true,
  },
})
``` 

In `dev.env` => `NUXT_PUBLIC_SITE_URL=https://web-dev.henoo.fr`

### 🛠️ To reproduce

https://nuxtseo.com/og-image/getting-started/stackblitz

### 🌈 Expected behavior

When I run the project in localhost with NuxtDevTools I have a good result in OG Image part. 

![image](https://github.com/user-attachments/assets/03f2511d-4e85-40a2-a256-7b9b890b8096)

But when I run it on deploy mode on my serveur with a docker I have this adress in my `og:image` balise : `https://web-dev.henoo.fr/__og-image__/image/event/invitation-ab3f0601-eb9c-41ad-946f-13f151234955/og.png`

The format seem to be in the same format in localhost but here I have the following result : 

> 500 Image size cannot be determined. Please provide the width and height of the image.

![image](https://github.com/user-attachments/assets/6ca425c3-e85f-4e2b-8c5e-0b012b08ec81)

### ℹ️ Additional context

I don't give a reproduction because it is only present on my dev server. I already try to create a new Nuxt project just for try this module but in localhost it's working fine...

**Comment by JulienHenrotin** [comment]
Okay I find something ! 
I changed my OG image template and I define width height and sizes in nuxtImg 

```html
<template>
  <div class="h-screen w-full flex flex-col items-center bg-cover bg-top bg-no-repeat" :style="{ backgroundImage: 'url(https://henoo.fr/pictures/illustrations/landing/cloud.png)' }">
    <div class="flex flex-col items-center flex-grow justify-center">
      <!-- edited this balise 👇 -->
      <NuxtImg
        v-if="picture"
        class="size-40 rounded-full mb-6"
        alt="user profile picture"
        :src="picture"
        width="150"
        height="150"
        sizes="xs:200px sm:210px md:220px lg:230px xl:240px xxl:250px '2xl':260px"
      />
      <div class="text-3xl text-center !font-semibold my-6">
        {{ userName }} t'invite à sortir
      </div>
    </div>
    <div class="mb-6">
      <NuxtImg src="https://henoo.fr/logo/logo_text.png" class="h-12" />
    </div>
  </div>
</template>
``` 

Know I don't have the 500 error. But unfortunately the image whose tag I've modified doesn't appear in the final image. 
I looked at my server logs and I have : 
`Can't load image http://web-dev.henoo.fr/_ipx/s_500x500/https://filesdev.henoo.fr/user/16616_1721310762248?1722417805412: fetch failed
`

If I load the full link in my browser I get the image. That's all that's left. The server-side module can't get the image.

**Comment by harlan-zw** [comment]
Please just use an img tag, I think NuxtImg has issues

**Comment by JulienHenrotin** [comment]
**Yeah it's what I tried it's working fine now 👍**

It's weird because the second <NuxtImg> works properly. 

_In any case, thank you very much for this package 🩵_

<details><summary>**Final code**</summary>
<p>

```html
<template>
  <div class="h-screen w-full flex flex-col items-center bg-cover bg-top bg-no-repeat" :style="{ backgroundImage: 'url(https://henoo.fr/pictures/illustrations/landing/cloud.png)' }">
    <div class="flex flex-col items-center flex-grow justify-center">
      <img
        v-if="picture"
        class="size-40 rounded-full mb-6"
        alt="user profile picture"
        :src="picture"
        width="150"
        height="150"
      >
      <div class="text-3xl text-center !font-semibold my-6" v-text="`${userName} t'invite à sortir`" />
    </div>
    <div class="mb-6">
      <NuxtImg src="https://henoo.fr/logo/logo_text.png" class="h-12" />
    </div>
  </div>
</template>

<script setup lang="ts">
withDefaults(defineProps<{ userName?: string, picture?: string }>(), { userName: 'Ton pote', picture: undefined })
</script>

``` 

</p>
</details>
