### ISSUE TITLE
feat: Support Arabic language

### ISSUE THREAD

**Issue by jafarkzemit** [nuxt-modules/og-image#252]
### 🆒 Your use case

- [ ] using Arabic language(Right to Left) for text  doe not affect correctly on provided og image, actually no effect displayed.

### 🆕 The solution you'd like

as English text displayed on provided image, the Arabic  text should displayed on right to left direction.

**Comment by MickL** [comment]
I assume this might be a restriction of the renderer used, [Satori](https://nuxtseo.com/og-image/guides/satori)? There is an open issue over here: https://github.com/vercel/satori/issues/74

You could try [Chromium](https://nuxtseo.com/og-image/guides/chromium) but it is way slower.

**Comment by harlan-zw** [comment]
As mentioned above, this is not something supported with the Satori renderer and the only work around is to use the chromium renderer.

Thanks Mick!

**Comment by Saad5400** [comment]
Nothing about this? ):

I was able to do a workaround like this:

```vue
<script setup lang="ts">
const props = defineProps<{
    description?: string;
}>();
const descriptionRender = h('div', { class: 'flex flex-row-reverse flex-wrap text-5xl px-18' }, props.description?.split(' ').map(word => {
    return h('span', { style: `width: ${(word.length + 2) * 20}px`, class: 'py-1' }, word);
}))
</script>

<template>
    <div class="px-4 py-16 text-[#298287] bg-black size-full">
        <!-- <component :is="titleRender" /> -->
        <component :is="descriptionRender" />
    </div>
</template>
```

But it's still not that good, each word has different spacing than the word next to it ...
