### ISSUE TITLE
fix: Build error for cloudflare-pages: no such file or directory, open '@css-inline/css-inline-wasm/index_bg.wasm'

### ISSUE THREAD

**Issue by MickL** [nuxt-modules/og-image#257]
### 🐛 The bug

I upgraded to latest `@nuxtjs/seo` `2.0.0-rc.18` that uses `nuxt-og-image` `3.0.0-rc.64` and now I get the following error on build using `NITRO_PRESET=cloudflare-pages nuxt build`:

> ERROR  ENOENT: no such file or directory, open '/Users/mick/git/frau-dora/apps/website/@css-inline/css-inline-wasm/index_bg.wasm' 

I dont use <style> tags and do not have any inline styles. I just use Tailwind classes.

### 🛠️ To reproduce

I made a minimal reproduction repo:
https://github.com/MickL/og-image-build-bug

**Comment by MickL** [comment]
@harlan-zw May you take a look? It is kinda critical because apps dont build anymore, all our pipelines are broken and should be of everyone that is using nuxt seo.

**Comment by harlan-zw** [comment]
Hey, thanks for reporting this. I've pushed up a fix in v3.0.0-rc.65.

**Comment by modbender** [comment]
Having this error on vercel build too.

```
nuxt build --preset=vercel_edge
```

**Comment by harlan-zw** [comment]
If your clear the lock file and re-install the deps it should install the latest og image with the fix.

**Comment by MickL** [comment]
Work again, thanks for the quick fix!
