### ISSUE TITLE
help: How do I switch to non-default renderer Chromium?

### ISSUE THREAD

**Issue by robmontesinos** [nuxt-modules/og-image#269]
### 📚 What are you trying to do?

I'm having trouble prerendering og-images for a fully static site. I tried to change to Chromium render but cannot find how to do this in the documentation - I'd like to compare Chromium to Satori and am unable to.

### 🔍 What have you tried?

In nuxt.config.ts, I added the following:
`  ogImage: {
    zeroRuntime: true,
    defaults: {
      extension: 'jpg'
    },
    compatibility: {
      prerender: {
        chromium: 'on-demand'
      }
    }
  },`

I still see Satori mentioned in the error messages, i.e. it made no difference to the 'nuxi generate' process.

### ℹ️ Additional context

I appreciate any help. Thank you

**Comment by harlan-zw** [comment]
Hi @robmontesinos, sorry the docs for this weren't very good.

To use chromium as the renderer you should do one of the following:


```ts
export default defineNuxtConfig({
  // sets the default renderer to chromium
  ogImage: {
    defaults: {
      renderer: 'chromium'
    }
  }
})
```

```ts
defineOgImageComponent('MyComponent', {
  renderer: 'chromium'
})
```

**Comment by robmontesinos** [comment]
@harlan-zw Thank you so much Harlan. It's funny that you mention that because I just noticed and completed the switch. Rock on bro!!
