### ISSUE TITLE
fix: og:image, og:title and og:description not showing on copy/paste of url to facebook in nuxt-ui-saas-deployment

### ISSUE THREAD

**Issue by LutherApp** [nuxt-modules/og-image#271]
### 🐛 The bug

The bug is:
1. No og-image or "social-card.png" shows 
2. No og:title or og:description shows
3. Five TypeScript errors when typeCheck is enabled.

I have a 100% clean `nuxt-ui`-saas-template that have the following `meta`-elements (screen clip):
![Image](https://github.com/user-attachments/assets/17c77384-d154-4b0a-b293-94ed814e3a23)

## Nothing of this shows on facebook
![Image](https://github.com/user-attachments/assets/bff82b6c-f926-4a19-8ec4-c2041d7c7fac)

## Comment
`Nuxt-UI` says that these have to be an issue with `nuxt-og-image`. 
https://github.com/nuxt/ui/issues/2415#issuecomment-2425321223

Can you please check it out, if these is a problem with your package?

### 🛠️ To reproduce

https://stackblitz.com/~/github.com/LutherApp/codespace-project
OR
https://github.com/LutherApp/codespace-project

### 🌈 Expected behavior

1. Expected that the og-image or `public/social-card.png` shows in facebook
2. Expected that og:title and og:description of the page shows in facebook
3. Expected no TypeScript errors when typeCheck is enabled 

### ℹ️ Additional context

I have the newest `nuxt-og-image`-package, v3.0.6.

NB! When you check out the view of the official Saas-Template here; 
https://saas-template.nuxt.dev/blog/cryptocurrencies
you can see the title of the blog-page[^1];
![Image](https://github.com/user-attachments/assets/5d556bb9-768e-4693-b328-dad5719d0de3)

This you don't see (see the first picture above) when you go to my 100% clean saas template, deployd on vercel: 
https://codespace-project.vercel.app/blog/cryptocurrencies

In my 100% clean saas template you only see the domain name, not the title or the url to the page.

[^1]: When you copy/paste the url to a facebook-post.

**Comment by LutherApp** [comment]
Can I please have a comment on the last updated comment?

## Facebook Sharing Debugger
Using [Facebook Sharing Debugger](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fcodespace-project.vercel.app%2Fblog%2Fpyrenees) give this result (on my 100% clean nuxt-ui-saas-template):

![Image](https://github.com/user-attachments/assets/ee2d869b-f991-4559-a8e9-da9be60052a0)

Ref: https://github.com/nuxt/ui/issues/2415#issuecomment-2428032780

**Comment by LutherApp** [comment]
# URL is wrong for og:image and twitter:image
Here is a screen clip from [Facebook's sharing debugger](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fsaas-template.nuxt.dev%2Fblog%2Fasian-cuisine)

![Image](https://github.com/user-attachments/assets/8dba080b-822a-4059-8979-9f41bf1d8b10)

Inspection of "og:image" meta element shows that it have this content:
https://305f69f9.saas-sgoa.pages.dev/https://picsum.photos/id/490/640/360

Here we can see that there is two `https://`-strings in the `og:image`-content field.

URL for twitter:image have samme url-error as og:image.

**Comment by harlan-zw** [comment]
This is indeed a Nuxt UI bug, I've replied to it there.
