### ISSUE TITLE
help: Emoji in props

### ISSUE THREAD

**Issue by kicaj** [nuxt-modules/og-image#278]
### 📚 What are you trying to do?

Use emoji in props (i.e. title)

### 🔍 What have you tried?

I try title like "lorem ❤️ ipsum", but the results is:

"lorem
❤️
ipsum"

Using emoji always breaks the lines, why?

### ℹ️ Additional context

My first experience with og-image.

Added to existing Nuxt UI project.

**Comment by harlan-zw** [comment]
Hi, this is an issue with the Satori renderer, see https://github.com/vercel/satori/issues/484

Unfortunately there isn't a fix for this besides hacking away at the HTML / CSS until it looks how you want OR just using the chromium renderer.
