### ISSUE TITLE
help: Nuxt UI components

### ISSUE THREAD

**Issue by kicaj** [nuxt-modules/og-image#279]
### 📚 What are you trying to do?

I would like to use Nuxt UI components, but always get error 500.

**Comment by Orgazmic** [comment]
Hi there! 👋
Run the command: 
`npx nuxi@latest module add ui`

This command will automatically install and configure the module in your nuxt.config.ts file.
Once that's done, you can start using Nuxt UI components like this:
`<template>
  <UButton>Button Text</UButton>
</template>`

After making these changes, restart your development server using:
`npm run dev`

**Comment by harlan-zw** [comment]
Are you able to provide a reproduction?
