### ISSUE TITLE
fix: content may not be a string

### ISSUE THREAD

**Issue by mz-dfhp** [nuxt-modules/og-image#294]
### 🐛 The bug

tag.props.content.startsWith is not a function

### 🛠️ To reproduce

https://nuxtseo.com

### 🌈 Expected behavior

The content may not be a string and you need to add a judgment

**Comment by harlan-zw** [comment]
This isn't a valid reproduction, however, I'm guessing you're trying to use a malformed og image path. I've pushed up a fix to handle this.
